---

- hosts: all
  become: true
  tasks:
  
  - name: install apache2 and php packages
    yum:
      name: 
        - httpd
        - php-fpm
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and php packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
